language: rust

rust:
  - stable
  - beta
  - nightly

cache: cargo

jobs:
  include:
    - stage: lint
      rust: stable
      cache: cargo
      install:
        - rustup component add clippy
      script:
        - cargo clippy --all -- --deny clippy::all

    - stage: format
      rust: stable
      install:
        - rustup component add rustfmt
      script:
        - cargo fmt --all -- --check

    - stage: deploy
      branches:
        only:
          - master
      rust: stable
      install:
        - rustup target add wasm32-unknown-unknown
        - bash <(curl https://gist.githubusercontent.com/janbaudisch/8074416b864dc357145e649449acb42d/raw/74f6c3d3bdca8b41fd0617e8992c078aec80966d/install-cargo-web.sh)
      script:
        - cargo doc -p heron --no-deps --release
        - cargo web build -p heron_web --release
        - mv target/doc dist
        - mkdir dist/demo
        - mv target/wasm32-unknown-unknown/release/heron_web.{js,wasm} dist/demo
        - cp heron_web/static/index.html dist/demo
        - cp heron_web/static/style.css dist/demo
        - cp .travis/CNAME dist/CNAME
      deploy:
        provider: pages
        local-dir: dist
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        name: flyingB0tat0
        email: bot@baudisch.xyz
        keep-history: false
        allow-empty-commit: true
