language: rust

rust:
  - stable
  - beta
  - nightly

install:
  - rustup target add wasm32-unknown-unknown
  - .travis/install-cargo-web.sh

cache: cargo

script:
  - cargo build --verbose --all
  - cargo test --verbose --lib
  - cargo test --verbose --example cli
  - cargo web build --verbose --example web

jobs:
  include:
    - stage: lint
      rust: stable
      cache: cargo
      install:
        - rustup component add clippy
      script:
        - cargo clippy --all -- --deny clippy::all

    - stage: format
      rust: nightly
      install:
        - rustup component add rustfmt || cargo install --git https://github.com/rust-lang/rustfmt --force --bin rustfmt
      script:
        - cargo fmt --all -- --check

    - stage: deploy
      branches:
        only:
          - master
      rust: stable
      cache: cargo
      install:
        - rustup target add wasm32-unknown-unknown
        - .travis/install-cargo-web.sh
      script:
        - cargo doc --no-deps --release
        - cargo web build --example web --release
        - mv target/doc dist
        - mkdir dist/demo
        - mv target/wasm32-unknown-unknown/release/examples/web.{js,wasm} dist/demo
        - cp examples/web/static/index.html dist/demo
        - cp examples/web/static/style.css dist/demo
      deploy:
        provider: pages
        local-dir: dist
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        name: flyingB0tat0
        email: bot@baudisch.xyz
        keep-history: false
        allow-empty-commit: true
